### ISSUE TITLE
Add Proper Unit Test Coverage

### ISSUE THREAD

**Issue by gemanor** [permitio/permit-cli#12]
This issue is about getting to 90% coverage for the Permit CLI. The current tests use only Node test runner and do not pass completely, so the task is also to stabilize the tests and choose the right tooling for efficient unit test writing.

Acceptance Criteria:
* Consistlenlty passed unit tests that cover 90% of the code in the repository by the time of starting work on the issue
* Well-documented explanation of how to run and write the tests on the home page

**Comment by varshith257** [comment]
@quest-bot embar

**Comment by varshith257** [comment]
@quest-bot embark

**Comment by varshith257** [comment]
@quest-bot embark

**Comment by sachinks07** [comment]
@quest-bot embark

**Comment by Neptune650** [comment]
> This issue is about getting to 90% coverage for the Permit CLI. The current tests use only Node test runner and do not pass completely, so the task is also to stabilize the tests and choose the right tooling for efficient unit test writing.
> 
> Acceptance Criteria:
> 
>     * Consistlenlty passed unit tests that cover 90% of the code in the repository by the time of starting work on the issue
> 
>     * Well-documented explanation of how to run and write the tests on the home page

@gemanor How do you feel about using [Jest](https://jestjs.io) for the tests, if we use it, I can start working on this right away. Also should we also use something like [Codecov](https://codecov.io) together with Jest for ensuring coverage, or just Jest with GitHub Actions is fine?

**Comment by varshith257** [comment]
@Neptune650 I have done progress on it integrating Jest. Just left with the task of increasing code coverage :)

**Comment by Bhavyajain21** [comment]
@quest-bot embark

**Comment by gemanor** [comment]
Seems like @varshith257 is the only one working on it. @sachinks07 are you planning to submit something or can I assign @varshith257

**Comment by varshith257** [comment]
@gemanor I think you an assign me. I have already covered good coverage of 85% as of now

**Comment by varshith257** [comment]
I think there are few bugs in login.tsx and policy.tsx, I think there needed fixes

**Comment by sachinks07** [comment]
@gemanor You can assign to @varshith257

**Comment by naaa760** [comment]
@quest-bot embark

**Comment by naaa760** [comment]
/attempt #12

Hello @gemanor :)

I want to work on this issue.
Thank you!

**Comment by aegroto** [comment]
Is there any work left on tests? I am willing to contribute if needed.

**Comment by Himasnhu-AT** [comment]
hey @gemanor, is this issue still open, else i can work on it.
is it okay if we use jest, as its in typescript, that would be best, according to me.
Its even use in NestJS.
They provide unit, integratin and end to end test which we can execute, with built in coverage checker and nice terminal UI

Few resource on how these test case looks:
https://github.com/Himasnhu-AT/scrapi/blob/main/apps/backend/libs/fetch/src/scrappers/axios.scrapper.spec.ts

Let me know your views on it

**Comment by Abiji-2020** [comment]
/attempt #12

quest-bot embark

**Comment by ARYPROGRAMMER** [comment]
@quest-bot embark

**Comment by gemanor** [comment]
Hey @Abiji-2020 - do you prefer your bounty in Algora or Quira?

**Comment by Abiji-2020** [comment]
> Hey @Abiji-2020 - do you prefer your bounty in Algora or Quira?

isn't this issue has bounty on both. I have accounts on both 😅

**Comment by gemanor** [comment]
It was a mistake that we put it in both :)
Please let me know the one you prefer

**Comment by Abiji-2020** [comment]
In both same amount means i prefer algora or like if there will be
difference i go with quira

**Comment by gemanor** [comment]
It's about fees we have with the platform. Will get you the Quira one so it will be higher..

**Comment by gemanor** [comment]
Thanks for your contribution @Abiji-2020

**Comment by Abiji-2020** [comment]
Waiting for next issues ❤️
