### ISSUE TITLE
Support Attribute Based Access Control in the Permit Check

### ISSUE THREAD

**Issue by gemanor** [permitio/permit-cli#14]
Add the possibility to pass attributes instead of strings to the `permit pdp check` function

Acceptance criteria:
- Add a capability to pass user/resource attribute to the CLI call in a friendly way
- Keep the current functionality in place
- e2e test that checks all the possible conventions to pass user/resource attribute

To read more about the check function: https://docs.permit.io/how-to/enforce-permissions/check

**Comment by Abiji-2020** [comment]
@quest-bot embark 

@gemanor we want extend the functionality to pass the attributes right?

**Comment by Abiji-2020** [comment]
![image](https://github.com/user-attachments/assets/b6feb599-ac6e-4220-b2ba-5beaccbaef1e)

# currently pastel doesn't support getting the values as attributes. So we need to get it as string and convert them as attributes before the CLI call.

**Comment by ARYPROGRAMMER** [comment]
@quest-bot embark

**Comment by Rutik7066** [comment]
@quest-bot embark

**Comment by Vikranth3140** [comment]
@quest-bot embark

**Comment by Adarsh0427** [comment]
@quest-bot embark

**Comment by gemanor** [comment]
Assigning @ARYPROGRAMMER as the first submitter of a PR for this
