### ISSUE TITLE
Permit Environment Management Commands

### ISSUE THREAD

**Issue by gemanor** [permitio/permit-cli#18]
We want to create a set of commands that will help users manage their Permit environments. The following is the skeleton of the commands required in this issue:

- `permit env select` - selecting a different environment and storing the relevant key. This should incorporate with the following issue and use the same components: https://github.com/permitio/permit-cli/issues/13
- `permit env copy` - will allow users to copy their existing logged-in environment to a new environment and change their active environment to it
- `permit env member` will allow users to add more members to their environment with proper roles

Acceptance criteria:
- All the above flows are impkemented
- Unit test coverage of 90%
- e2e test of the basic flow of each

**Comment by Abiji-2020** [comment]
@35C4n0r can we collaborate on this issue

**Comment by gemanor** [comment]
@35C4n0r In order to assign you to the issue, I would kindly ask that you share your progress on the issue and the design of your components/lib files for review. I will assign you after the design review.

**Comment by 35C4n0r** [comment]
@gemanor Since this issue depends on https://github.com/permitio/permit-cli/issues/13, I'll finish #13 first, then write a proposal for this. Let me know if that works! :)

**Comment by gemanor** [comment]
Works, but please try to write a proposal ASAP so I can assign you to it

**Comment by 35C4n0r** [comment]
@gemanor here is my proposal for this one =)

- We'll create a new file `env` in the `source/commands` dir.

- We will use the existing component built here in #28 https://github.com/permitio/permit-cli/pull/28/files#diff-de1a6861d1b4be5affe427a2fd0fd23ef364b77026866476f93ac87a2a56cdd6 for the `permit env select` command.

- For the `permit env copy` command we'll take user input via a component and flags: `--project` and `--env`

- For the above command we'll also create new methods to copy and switch the environment in the hooks here https://github.com/permitio/permit-cli/pull/28/files#diff-5fa375664b9f3623c65bd1c2b8e57435ee00a65b29b8545b7b94ef5202fed6dd

- We'll create a new `useUserApi` hook to add the users with roles, interactively or via flags for the `permit env member` command.

**Comment by Rutik7066** [comment]
@gemanor  I have one proposal for Login, sign-up, Environment management, and the overall app, if @35C4n0r doesn't mind.

**Comment by gemanor** [comment]
Hey @Rutik7066, as you saw, @35C4n0r already submitted a proposal for this one and PR for the other login flow. We are currently working on a first-come, first-serve model, so we will continue with him at this point.

Also, we have already based our structure on the Pastel structure recommendation, so there is no need for extra best practices for organizing the Node.js CLI app.

I'm more than inviting you to submit bounties on other PRs in this repo, or get back to that in a week in case @35C4n0r will have to cancel his attempt.

**Comment by gemanor** [comment]
@35C4n0r The proposal looks good, and you've approved continuing with it. 

Two comments: 
* The hook should be useMemberAPI because `user` is a different term in Permit (the end user who gets authorized)
* The copy environment API should copy and switch to the new one but does not require `--project` because the environment can be copied only inside projects. Please take a look at the following API doc and propose the command arguments. https://api.permit.io/v2/redoc#tag/Environments/operation/copy_environment
* Pay attention to the fact that you'll maybe have to grab a project token when switching environments (as we are now storing only the environment key). Please also include the design for it in the proposal.

As usual, please try to bring it ASAP so I can assign it to you.

**Comment by Rutik7066** [comment]
@gemanor no problem. I just wanted to ask one this that I have also raised the pr for the login and sign up flow. Will that be accepted. In that pr I have not changed the structure just solved the issue.

**Comment by Rutik7066** [comment]
@35C4n0r can we collaborate?

**Comment by 35C4n0r** [comment]
@gemanor, thanks for the feedback, here is the revised proposal:

- We'll create a new file `env` in the `source/commands` dir.

- We will use the existing component built here in #28 https://github.com/permitio/permit-cli/pull/28/files#diff-de1a6861d1b4be5affe427a2fd0fd23ef364b77026866476f93ac87a2a56cdd6 for the `permit env select` command.

- For the `permit env copy` command we'll take user input via a component and flag: `--target`, --`conflictStrategy` and `--scope`, which will copy the existing environment to the `target` environment.

- We will create a hook to get a project level access token with write permissions to copy the environment.

- For the above command we'll also create new methods to copy and switch the environment in the hooks here https://github.com/permitio/permit-cli/pull/28/files#diff-5fa375664b9f3623c65bd1c2b8e57435ee00a65b29b8545b7b94ef5202fed6dd

- We'll create a new `*useMemberApi` hook to add the users with roles, interactively or via flags for the `permit env member` command.

**Comment by gemanor** [comment]
@35C4n0r sounds good to me

**Comment by 35C4n0r** [comment]
Thanks @gemanor, I'll start working on it right away, my work will be based of the branch here https://github.com/permitio/permit-cli/pull/28.
