### ISSUE TITLE
Permit GitOps Flow Wizard

### ISSUE THREAD

**Issue by gemanor** [permitio/permit-cli#19]
We want to allow users who want to port their policy code from Permit to be managed in GitOps at their own environment, to use a wizard on the CLI that will configure the following: https://docs.permit.io/integrations/gitops/github/

Acceptance criteria:
- New command `permit gitops create github` is creating a flow that allowing users to use a private git repository to sync their policy from Permit
- 90% unit test coverage
- Demo video of the flow

**Comment by Abiji-2020** [comment]
@quest-bot embark , I would like to work on this issue.

**Comment by Abiji-2020** [comment]
@quest-bot embark

I would like to work on this issue.

**Comment by gemanor** [comment]
@Abiji-2020 please share your component/lib design for review so I'll assign you to the issue

**Comment by Abiji-2020** [comment]
I am following similar procedure from the link: https://docs.permit.io/integrations/gitops/github/

 - Initially creating a component to generate SSH key and the public key will be displayed to the user to copy and add it in the deploy keys.
 - We get the SSH URL from the user of the repo 
 - We ask the user in which project we want to create the flow and add it using the API calls, referenced in the API. 

This was my idea to implement it.

**Comment by Abiji-2020** [comment]
> Sounds like a good plan. Make sure please that you're making the ssh part a cross platform wizard

instead of taking ssh part from each computer, I am using a library to generate ssh keys. (https://www.npmjs.com/package/micro-key-producer) so it will be independent of platform.

**Comment by tarunpahade** [comment]
I would like to solve this bug

**Comment by hellzbarbie** [comment]
@quest-bot embark

**Comment by gemanor** [comment]
So far, @Abiji-2020 , is the only one to create a good start of a PR for the issue. Assigning it to them.
